"""empty message

Revision ID: 298e9a03eb67
Revises: 62bacc658daa
Create Date: 2024-03-26 21:05:28.216019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '298e9a03eb67'
down_revision: Union[str, None] = '62bacc658daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    seasontype_enum = postgresql.ENUM('PENDING', 'CONFIRMED', 'QUARANTINE', name='ReviewStatus', create_type=False)
    seasontype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('seasons', sa.Column('season_type', seasontype_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'season_type')
    # ### end Alembic commands ###
