"""empty message

Revision ID: 3430aeb39371
Revises: 90ae75b95f6a
Create Date: 2024-03-18 21:00:41.480979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3430aeb39371'
down_revision: Union[str, None] = '90ae75b95f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    animetype_enum = postgresql.ENUM('show', 'movie', name='AnimeType', create_type=False)
    animetype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('anime', sa.Column('_type', animetype_enum, nullable=False))
    op.drop_column('anime', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('type', postgresql.ENUM('show', 'movie', name='AnimeType'), autoincrement=False, nullable=False))
    op.drop_column('anime', '_type')
    # ### end Alembic commands ###
