"""empty message

Revision ID: 505bdba43992
Revises: 14a739fdb5ed
Create Date: 2024-12-23 02:01:20.069011

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '505bdba43992'
down_revision: str | None = '14a739fdb5ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('part', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'part')
    # ### end Alembic commands ###
