"""fix rating season_id foreign key and add constraint

Revision ID: 70c3d7ede669
Revises: 8b3127c1ce0a
Create Date: 2026-09-28 20:51:06.753896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70c3d7ede669'
down_revision: Union[str, None] = '8b3127c1ce0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('anime', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('ratings', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ratings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('ratings', 'anime_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_user_anime_season', 'ratings', ['user_id', 'anime_id', 'season_id'], postgresql_nulls_not_distinct=True)
    op.drop_constraint('ratings_season_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'seasons', ['season_id'], ['id'])
    op.alter_column('seasons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('seasons', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('seasons', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('seasons', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_season_id_fkey', 'ratings', 'anime', ['season_id'], ['id'])
    op.drop_constraint('uq_user_anime_season', 'ratings', type_='unique')
    op.alter_column('ratings', 'anime_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ratings', 'updated_at')
    op.drop_column('ratings', 'created_at')
    op.alter_column('anime', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('anime', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
