"""empty message

Revision ID: a4311f88dc30
Revises: c0074856ad37
Create Date: 2024-03-27 22:01:30.707533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4311f88dc30'
down_revision: Union[str, None] = 'c0074856ad37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###\
    with op.batch_alter_table('seasons') as batch_op:
        batch_op.alter_column('episodes',
                              existing_type=sa.INTEGER(),
                              nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seasons') as batch_op:
        batch_op.alter_column('episodes',
                              existing_type=sa.INTEGER(),
                              nullable=False)
    # ### end Alembic commands ###
