"""empty message

Revision ID: c0074856ad37
Revises: 298e9a03eb67
Create Date: 2024-03-27 21:32:21.078346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0074856ad37'
down_revision: Union[str, None] = '298e9a03eb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    seasontype_enum = postgresql.ENUM('SEASON', 'ONA', 'OVA', name='seasontype', create_type=False)
    seasontype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('seasons', sa.Column('type_season', seasontype_enum, nullable=False))
    op.drop_column('seasons', 'season_type')
    op.alter_column('anime', 'desc',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('seasons', 'desc',
                    existing_type=sa.VARCHAR(length=255),
                    type_=sa.String(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    seasontype_enum = postgresql.ENUM('PENDING', 'CONFIRMED', 'QUARANTINE', name='ReviewStatus', create_type=False)
    seasontype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('seasons', sa.Column('season_type', postgresql.ENUM('pending', 'confirmed', 'quarantine', name='ReviewStatus'), autoincrement=False, nullable=False))
    op.drop_column('seasons', 'type_season')
    op.alter_column('anime', 'desc',
                    existing_type=sa.VARCHAR(),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    op.alter_column('seasons', 'desc',
                    existing_type=sa.VARCHAR(),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###
